Reverted the script addition since it's not present yet on the remote server

diff --git a/.github/workflows/build-deploy.yml b/.github/workflows/build-deploy.yml
--- a/.github/workflows/build-deploy.yml
+++ b/.github/workflows/build-deploy.yml
@@ -70,11 +70,24 @@ jobs:
             export SERVER_HOST=${{ env.SERVER_HOST }}
             export SSH_USERNAME=${{ env.SSH_USERNAME }}
 
+            echo "Cloning/Updating repository..."
+            mkdir -p "${GIT_REPO_PATH}"
+
+            if [ ! -d "${GIT_REPO_PATH}/.git" ]; then
+              echo "Repository not found. Cloning..."
+              git clone https://"${ACCESS_TOKEN}"@github.com/"${GIT_REPO_USERNAME}"/"${GIT_REPO_NAME}".git "${GIT_REPO_PATH}"
+            else
+              echo "Repository found. Fetching latest changes..."
+              cd "${GIT_REPO_PATH}" || exit
+              git fetch origin
+              git reset --hard origin/master
+            fi
+            
+            echo "Setting correct ownership..."
+            chown -R "${SSH_USERNAME}:${SSH_USERNAME}" "${GIT_REPO_PATH}"
+
             echo "Making scripts executable..."
             find .github/workflows -type f -name "*.sh" -exec chmod +x {} +
-
-            echo "Cloning/Updating repository..."
-            .github/workflows/clone_update_repo.sh
 
             echo "Executing deployment scripts..."
             .github/workflows/build_docker_images.sh
